# Sidebar navigation

- label: Home
  link: '/'
- label: Triva Game
  link: '/play'
- label: API
  items:
    - label: 'Getting started'
      link: '/api'
    - label: 'Querying'
    - link: '/api/query'
    - label: 'Demo'
      link: '/api/demo'
- label: About
  link: '/about'
