# Sidebar navigation

- label: Home
  link: '/'
- label: Trivia Game
  link: '/play'
- label: API Docs
  items:
    - label: 'Getting started'
      link: '/api'
    - label: 'Querying'
      link: '/api/query'
    # - label: 'Demo'
    #   link: '/api/demo'
- label: About
  link: '/about'
